# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2d9ee5faca50bad922b3d4d65c0d2e2c0467848f4120ebdecebdda781f675d8ea9a0bf51ef9f0703038d386470ee2dd60d3bc95585a91adcd248797d436208e

test:
  secret_key_base: 37eb2eaf07ab05796935ee28f388f34f08d2bbdfc9e3f5d935cc4e486f8874b87d82e9e6a24c4f4adb20fcd6cfebd794257e2928c1bfc00ffc08ca7617aff790

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
